### ISSUE TITLE
Challenges in compiling SIMPL (Linux)

### ISSUE THREAD

**Issue by sdh4** [BlueQuartzSoftware/SIMPL#122]
Found a couple of minor bugs and other challenges getting SIMPL to compile from git as of last week (8/17/17):
   * Inconsistencies with hid_t, herr_t, and int32_t  (patch attached)
   * SIMPL could not be built against the OS-installed 1.8.18 version of hdf5; instead required building hdf5 from scratch with CMake, 
   * Dependency list is quite long... at least some components such as ITK look like they should be dependencies of DREAM.3D not SIMPL per the architecture page http://dream3d.bluequartz.net/?p=2688 It would be nice if it were possible to build SIMPL with some components disabled for those of us who might not need everything. 
   * Specifically ITK SCIFIO dependency was problematic because it is an out-of-tree component of ITK that requires a fully built ITK tree to rebuild (would have to have rebuilt ITK). I ended up disabling it 
   * building with gcc 7.1.1 (Fedora 26) seemed to require VCL_CAN_STATIC_CONST_INIT_FLOAT=0 or perhaps some compiler flag I don't know about; this was not autodetected and had to be troubleshooted. 

[simpl_compile_patch.txt](https://github.com/BlueQuartzSoftware/SIMPL/files/1242796/simpl_compile_patch.txt)

**Comment by imikejackson** [comment]
Which Linux distribution are you using? SIMPL should be able to be built against most system HDF5 installations.

Boost is no longer required for SIMPL. It was purged a while back. The page at http://dream3d.bluequartz.net/?p=2688  is out of date and needs to be updated.
 
The following should work:
cmake -G Ninja -DDREAM3D_SDK=/Users/Shared/DREAM3D_SDK -DSIMPL_USE_ITK=OFF -DSIMPL_USE_MULTITHREADED_ALGOS=OFF -DCMAKE_BUILD_TYPE=Debug ../../SIMPL

I think there is a issues somewhere to address turning off SCIFIO.

VCL_CAN_STATIC_CONST_INIT_FLOAT is an ITK issue and probably needs to be addressed in the appropriate ITK bug site.

We may have to create the proper Linux VM in order to test your configuration.

**Comment by imikejackson** [comment]
The DREAM.3D and associated plugin repositories have been checked to work when compiling **without** ITK and/or TBB,

**Comment by imikejackson** [comment]
The ITKImageProcessing plugin was updated with a CMake option to disable the SCIFIO module. By default it is on. This commit https://github.com/BlueQuartzSoftware/ITKImageProcessing/commit/446295e2c0e42aa2ab9ce026a6b2430392d043d9 makes the change.

**Comment by sdh4** [comment]
Thank you!!! 

 * I think the problem with the Red Hat provided VTK library is that because they did not use CMAKE for the build, they did not include the .cmake files, even in the hdf5-devel package. Maybe I should do an RFE to Red Hat/Fedora  to include those files even for non-cmake builds
  * The VCL_CAN_STATIC_CONST_INIT_FLOAT would be a VXL issue, not an ITK issue, no? But its rather bizarre as this flag was not set in VXL's own build, which should have been with the same gcc7 compiler. Maybe a compiler flags difference. No biggie. This issue at least documents the workaround.

My apologies; I missed the SIMPL_USE_ITK cmake flag
