### ISSUE TITLE
"Delete Data" filter not working properly

### ISSUE THREAD

**Issue by dumoulins** [BlueQuartzSoftware/SIMPL#25]
Something strange is happening with the "Delete Data" filter. I keep getting the error that the arrays I have selected to be deleted ".. cannot be removed because it was not found in CellFeatureData"! See the attached json file (I changed its extension into txt to trick the filter).
[ANG (SqrGrid) To Statistics.txt](https://github.com/BlueQuartzSoftware/SIMPL/files/900736/ANG.SqrGrid.To.Statistics.txt)

**Comment by imikejackson** [comment]
The root of the problem was the MinNeighbors filter which will remove any arrays of type "NeighborList<T>" if the MinNeighbors filter adjusts the number of features because a feature did not pass the criteria in the filter. I have made a note in the documentation for the filter. Since we can not fix this during preflight I adjusted the RemoveArrays filter to emit a warning instead of an error if the selected filter to delete was not found. My logic is that you wanted it deleted anyways do a warning should suffice. The larger problem is that if a filter in a pipeline needs that array then there will be problems (possible crashes) during execute.
 I am going to mark this bug as fixed and close it. The fix is in commit 2066d4424f9bcc23ed0e0ab8241fe73082b1a173 and will be integrated into the next nightly build.
