### ISSUE TITLE
Remove SIMPL_*_VARIABLE Macros from header files

### ISSUE THREAD

**Issue by imikejackson** [BlueQuartzSoftware/SIMPL#361]
In the pursuit of updating the SIMPL/DREAM3D code base to better adhere to the C++11/14/17 style guidelines I have prepared a huge patch the removes the following macros from all of the header files:

SIMPL_SHARED_POINTERS
SIMPL_FILTER_NEW_MACRO
SIMPL_STATIC_NEW_MACRO
SIMPL_STATIC_NEW_MACRO
SIMPL_TYPE_MACRO_SUPER_OVERRIDE
SIMPL_INSTANCE_PROPERTY
SIMPL_INSTANCE_STRING_PROPERTY

The macros are replaced with correct declaration codes and the actual definitions are then appended to the matching .cpp file. The change was made at first in an attempt to reduce compile times by reducing the number of macros. Turns out there was no real effect on the compile times but the style of the code base is closer “modern” C++ standards now. 

Any and all opinions on this very large change are requested. I am going to leave the macros in the SIMPLSetGetMacros.h file for codebases that I don’t have access to and the developer is certainly NOT required to update their codes. The “SandboxTool” that I created can be surgically run on a source directory if you want to update a plugin. With most modern IDEs having the ability to use “snippets” inserting new filter parameters or instance variables really is very straight forward.

**Comment by imikejackson** [comment]
code goes from this:

    SIMPL_FILTER_PARAMETER(DataArrayPath, SelectedArrayPath)
    Q_PROPERTY(DataArrayPath SelectedArrayPath READ getSelectedArrayPath WRITE setSelectedArrayPath) 

to this:

     /**
        * @brief Setter property for SelectedArrayPath
        */
        void setSelectedArrayPath(const DataArrayPath& value); 
        /**
        * @brief Getter property for SelectedArrayPath
        * @return Value of SelectedArrayPath
        */
        DataArrayPath getSelectedArrayPath() const;

        Q_PROPERTY(DataArrayPath SelectedArrayPath READ getSelectedArrayPath WRITE setSelectedArrayPath)
      private:
        DataArrayPath m_SelectedArrayPath = {};

and in the .cpp file:


    // -----------------------------------------------------------------------------
    const QString CalculateArrayHistogram::getNameOfClass() const
    {
      return QString("CalculateArrayHistogram");
    }

    // -----------------------------------------------------------------------------
    QString CalculateArrayHistogram::ClassName()
    {
      return QString("CalculateArrayHistogram");
    }

**Comment by mmarineBlueQuartz** [comment]
I definitely prefer this.

In terms of "FilterParameters", I'm not much of a fan of looking up which macro exists for getter-only, private, and other variants of SIMPL_FILTER_PARAMETER.  If the one I want is not already in the header I'm working on, it's been faster to write the corresponding method myself.  This also allows default values to be specified in the header rather than updating initializer lists in each constructor (usually only one, but it's easy to forget when there are more) while switching back and forth with the header to make sure the order is correct to prevent warnings.  This also holds true when updating a default value when there are multiple constructors.  Due to this, I feel there are more drawbacks to using the existing macro than writing the "modern" method.  This applies to SIMPL_INSTANCE_PROPERTY and SIMPL_INSTANCE_STRING_PROPERTY, which are already longer than writing out the private value in the header.

I'm used to seeing static Create methods, so SIMPL_STATIC_NEW_MACRO already feels like it's been fazed out to me.

Other than getNameOfClass(), everything else in SIMPL_TYPE_MACRO_SUPER and its OVERRIDE can/should be replaced with type_traits.  Arguably, getNameOfClass() can probably be included in that list as well.

SIMPL_SHARED_POINTERS seems to encourage including additional headers rather than forward declaring types in other headers.  This might not save much time during compiling since AbstractFilter and the DataStructure are required by every filter, but it isn't good practice to include everything in your header unless the header does indeed need it.  Forward declarations and `using *ShPtr = std::shared_ptr<*>;` would be enough to replace those types in other headers.  Other than encouraging lazy programming, I don't have a problem with it.

**Comment by imikejackson** [comment]
Merged in long ago
