### ISSUE TITLE
RotateSampleRefFrame copies data unnecessarily

### ISSUE THREAD

**Issue by JDuffeyBQ** [BlueQuartzSoftware/SIMPL#428]
In `RotateSampleRefFrame::execute`, the appropriate data must be copied from the original data to its new position in the rotated geometry. The current implementation resizes the original array and copies the data, and then additionally creates a new array to copy the data into the correct spots. Only the second array is actually required, and the first resize is redundant. Additionally the array copying can be parallelized.

**Comment by imikejackson** [comment]
Addressed in cc5fa4bc2

A new array is allocated at the proper size during execute. SIMPL will now perform the copying in parallel at the DataArray Level. One CPU core is assigned to each DataArray to do the copying.

Parallelization of the actual data array was explored but turned out to be slower then serial. The code was left in if someone else wants to try it again.
